apiVersion: v2
name: task-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.4
icon:  https://www.gravatar.com/avatar/87e53d9
maintainers:
  - name: michaelappiah2018
    email: 8055cansave@gmail.com
    url: https://github.com/Terre8055


dependencies:
- name: mongodb
  version: 14.x.x
  repository: "https://charts.bitnami.com/bitnami"

