apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts 
    targetRevision: 56.6.2
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          grafana.ini:
            smtp:
              enabled: true
              host: smtp.gmail.com:587
              existingSecret: grafana-secret
              from_address: 8055cansave@gmail.com
              from_name: Demo-Boss
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            hosts:
              - grafmike.chickenkiller.com
            path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - ServerSideApply=true


