{{- if .Values.serviceCluster.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: {{ .Values.cert.clusterIssuerName | default  "letsencrypt-staging" }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.cert.config.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: {{ .Values.cert.httpIngressClass }}
{{- end }}
