apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image:  {{ .Values.imageName }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: task-manager-mongo-conf
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret
                  key: uri
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 64Mi
              cpu: "0.2"
        - image: nginx:1.22.0-alpine
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: default-conf
              subPath: default.conf
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 64Mi
              cpu: "0.2"
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: default.conf
                  path: default.conf
              name: nginx-sidecar
            name: default-conf