apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: default
spec:
  encryptedData:
    password: AgAdQx8K6zSWzwOYrlmWSqBXS1vscuNf0SvBYwyLhLJ9/zlXhILscTQSjpct5EJmj0ih+P53oPVL/xfDhbXAmCSMga4KwjX+ooMkbkNl0w/ixNKULsImCFkqlJdAOT6Lbn1x3uXPs0upGmqdQyptIFdN6AN4JdhC+jROKS4AvaeGZot81xJcgzlOS/lnly/bcAt3HtbtOOywhPMjX0OAdGGl3b5GFrA2zFIkajf9ObQuY1p7iKJffqTnFUu3Iny0HXyrwFlPMbkIg7jcWgE/5c9vhTnZM3ma/3Ct7Fg3Dp5Iw2ZFbFa8MhIAMD2oCb3Y4GMRgWYzs+QsIPTKaom/VvYIHs7pPRDCGyEC+2ELFzkA1Hab7+ftTjtTXFOpIW1lEQ3126Izu5szF/JGg3P9dhA9hJizNkGUm8GjHqk2pxIGZ5gC+ruSNUXy3J/twxfECchief4e/z2NzQlgjnLOWV2sM3arlnt8uj0YfqMUHqY+P21XCQdziSZFX6bZzhhH063h51f2zk7YhSgIkmR6dO5v35Aswh58hcD0uKI+ynLwbovHfclGB6sVLCMc3ph3/+2oTUu2p7nL5dnGhFcAO8SWHvmQgaH95jpN3MuKwAjy6NVYPHxOqVljqAf1QV9NBYUKYUzEXxPw2dowefNF6Aw3wKv3T5hnr11zj31Tol3eoL6qR4e8c911hN/owuL/dFCLIcuVPuoZvmuDh72vPird
    user: AgBYfLYH458AQixoAE9bBjyYhu+SYRQEWP/zGI0iLTi+z4SR01DbuTHmgxA3cJxP7KXc6li0tYC9Db1uy3VNTAWwVFJxDgQ6ETmxIug/jU+R11G5ure2/YikgaeTOwyTz/qcCSuEFKvtBDw7z19A0dQFOtHMLlTsOiKsL5Ta4G8mw54e5TLHYL4kutpTs3lzW+is3QUL9bTC8whUTk802A80OSvR1vVTUv5AV7l7R/y6B01PdkVLjY3NGQt034cmk9nyI2pzyLpAM7ZUVg5C2VfdCRcWrAk6Xt6tiZ4FgHvJ5zwA1Lv6QAABwfVLKkraHKcJzQ1tc+fqG+BSY9UYZCbO//8Y/uD3YCsZb/wink28zMz82k61yoyWhYmHxu/3iA/LzpiFv9FQjxRw+6af2OOlA9iL/bNqSqjVbFOGyN1AOjrSw1hIF4yd/8H0XaxdFCTxL20LEht6e9GhCc1v5wrq4OSghk5/PGPTHL/ejzgl0JIO0NGYBcpkb9bvL8ZaDt8xaVE71lTkRmzPo8wAoe9qWmDEJTy1KH/4Rh1Yq5bYj8bWNW5OaXi3PA4dVfIaaX9Kp1HmkLpDkgEEuvvzXrr3JWJ/E0Y8LTPud0XTYx9JnrtxNchxqEk6FATf4zvY6ibZEpnzbB7cx3lV6cPVeJUV1/J3p+NcFHXkYKR7oi8zgTsB+oG2fHmVe5m52IrlXPkdpIFWtADNEDVG0V/3DS/tYxaB/Bc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: default
    type: Opaque

