apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: kube-system
spec:
  encryptedData:
    mongodb-replica-set-key: AgBpZpkMt2cunQea6UQrEJVuUxVT7V1KQTSiZGtMmAuMbN5BO64He1RjCFhLTSlSxvJQI017UFngWgtJN8OUp8QT8eVpx+N5bSexrW+J0gWpo25yXA4P0ghIsM77nV5cbUTMRo+vsDK0U7VPjYJpCp3248G8a0zq2wqcm/nR1m1iYrGpQtsmLElA4tSDoMzLQPBBI0YLgXXVC6TEm9ZAnHmPLL9dZuTH2K9t78y0suvGcbRp01PCYu3/DeURo1nhFZSs96XxeTTh90uHaXjAFih6Lp8sk3J5rKk9iJB0zUvubeZ9zAv5f/EUhZJ3MZrGLxp6CrDOxzoB+NCWl/zwvAWijgvFoYTZi0m/h718+2LnH3/qHjbOsKEg1JaMWSW3Ngs22EhT+cKZKu+6GNw82eu3rOOja54bR4J0OPvQAifqI8TIzsXBzevDtsjqEx6eaAetly+hq9LvgXa3IingxHl5wg7PkSC/VGYSOeQNJ+EHr5YSE7S6bDN2RCTmfZixLmyfivOcHNiVIQyyXBgpxcO8B6OpgqgnMbPEp4KnYne/8RHA+Pi5PwNbzumqzDP2+xeNHReJveoGaGdgBAkD6T4CfOeg0HxCUSkof3TlH0DGdly7QgQscRuaLWquNvuzjJu0I1PX2ogBr9RlrVQNvhqVvsMO5TLzlS6emwpH1k3ZuedWAyuLnlBmG21zTsiR7rtJSXbLXTY4WLvR
    mongodb-root-password: AgAH2DHNL42n6dRJhpDtm4+XpvPDLFj9/M8jFahRGdeB55gTozuPAhwfC2xBNZuRqK8zLT9PQF2NumOIZLPLGT0HZwLSRxDkJjmHo9wOt1CDR6JuWJl7SbjgSHNXyi9J9+/BBV5+jnWYx4nOUzUTd/nRMfjuNdiQ97bex1rlxFoFOtQtZK+21tkQemGvoRwoLGSS8d5z7IvNLzXOvCdTlPCDdnDBxA730OozSUarzxRk8U30ArL1PX1hVCJ2NR/cmFp/ngsQ7bzKPk4NbQFXKj+h4+PeABopw28wqUVFw7ytN2AV7MaH4Xo0omzka2lCaaUaL9M1IEI0LNZizkqvkV9aPGUot02SDjVp4mA3F5jyEvrF+i68jVzjrwbMBEjNafIMW5d530QSaiVJvS2MQ7LvEQGUPsv3xCYaU8cezxcnh/rS0yzaIpHedaTtSa3qYGFWvfyYwVX+bvKdr68dDQkJmW0vycVmisQKcNCQ6jWHY+c+ktcjC48Z5o/cBm0E7VMIiqRGn/6IqKz7lGCw3ZfMR+oC3V/vtxJ5+J87zfAc+sNW612VrUv3CuhqAAcNGUjHMXkq+q8wHqfonGhOvwsBmzyB7RyHLPPddcUbZzlKDGar7yc+3uIqTCVKrEuA6Vy9GF+jFLuHKnO+6Z+1RLCzlr5qhNegAARD971rWWoaNUTMnrUdzfHCcnv3hLukl/BMmmaIhdm7ISQu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: kube-system
    type: Opaque

