apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    mongodb-replica-set-key: AgB9c8Z18lqkkMhThuALurMyFliDbDr+YFAsw7Kfd4JgKPDowJPkzn6+3+dwvF2tX9dsdVTAMyXGqiuG680C4x2EeW0VJQrPnpPWEpUXLqYI3bin70MNLOadKUiwSRbLQNsB+HYu4/opkKIKuOmBoj730myF66rLxAntYcjruwKulIBH0dMrx1eegqCThHdLkEQ1cNO6otaiGBwJSFkyZOT6aqQwXD523ZIh63wj3epnx5PFgg/Q9rgBHsoH8cnOrpKq7O1Te+1avGrHMGe5X0LfyW8pMGXzG533xDTNG1Hx83+edpWVpK66Dmqy4TifW2jONDlXETQm2sxBGbu0LltfHE2w7AUC+FuQFOljeDmoKLYu7VQUgkpqyuycY0Rws6/8lhm2b4prrhu9TnK4nUeHB84VX4R6ZiLdAcVAW9MlpX0O6d5MT5kPN2DV1P0h98GNc8yiPP2dcKWq00RZudwxlNDod5jouqgslmbbDh/C/GTJySnEzr9kYhW4npsFi1bFkynAqS1PFIUNdxLIhdzIA4A8sXMVO4PGrOB2B3jJweGKgRF6jbQppXBl/grEM0qifQjRjtQ5uBztlZBeXHmvWY4bfyXVscX73VcoSZCpvgPKtQcgpzU7a6xYJ+OVHxLP841YLh/dY5bNxlvmJiBNYgaqM/S4xLJsaBHE2xUp1rZhEr2pqnkjKbT1BqeuRVzYsd3+fi2ZhiTH
    mongodb-root-password: AgCQVYwrsYuhKftqaCSHhWjlSPGucUdcelS/vWcG0hWTRi2ru9JaAJoAnxMho4gCQwA9YXb06B0DLJDZZcL6LLVVPf8BLDzHkdfRebqlV30Qs/mCkwWGrygCGVQ5j+T0OrpbRla+5FfSvUjSYy2Epv9DGU/MWsdl3Wb3UU5nEgIzfgY2E89jfKELC6/VdobP26FkybWpEXrfjuRVHKr//G9+YbgArM+ihj6ZKB9oDgTriXeviz58hC9QJ6YDWN+iibX3FEYoT49So2A2h398pXwS9tHpdSofKOYKRL9Vyn5y9q0D3Kh3bpyfoT8IjBsB0BwXWErKrBzcPAkb+MjPTH7CblNptN4RvN7c+zW8v3lzWkr92Y6zRRjpcV6uvf/l/0kag2CZR0sBf6tqeUxZMP6nll0YN+VGO6P4v0R8V66v0k6KcKv9x7nwgiek71i9LRB1h355gabixJTyvDsZxHD82Xvn24qJ5hLjzJrOZEu0+EkM7n8HTToCNN1vaqr4a+T8wOl846GuhmlFNf0B7m9022a5YcJ+UDXmSEdreljQqyw1NALQzZBtlpNOVMuRVAqVGtqy7noj+W9Gr3i+AHUMyaYR3zPhLqyk3MFlItUMrdKHK2ji9sf8gifuvCMkl1otRpM9xNe06/NjBRW2c92nwPFOY0rH1KB0mGsqLOLz6W2HcGSmVWQ25y//r3jjuZifrXrpRCi4hrTY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

