apiVersion: v1
data:
  nginx.conf: |+
    worker_processes 1;

    events {
    worker_connections 512;
    }

    http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80 default_server;

        location / {
        proxy_pass http://0.0.0.0:5000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static {
        alias /usr/share/nginx/static;
        }

        location /metrics {
        proxy_pass http://0.0.0.0:5000;
        proxy_redirect off;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-sidecar